name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite UTC
  workflow_dispatch:      # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        id: snake
        with:
          github_user_name: izaabs
          outputs: |
            dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
